<?php
// Includes functions for common db queries.
require_once dirname(__FILE__) . '/includes/db.inc';

/**
 * Listening to form alter hook, to connect autocomplete js
 *
 * @param array  $form
 * @param array  $form_state
 * @param string $form_id
 *
 * @return void
 */
function flat_lang_autocomplete_form_alter(&$form, &$form_state, $form_id) {

    $allowed_forms = ['flat_deposit_cmdi_form', 'flat_bundle_update_cmdi_form', 'flat_collection_add_form', 'flat_collection_update_form'];

    if (in_array($form_id, $allowed_forms)) {
        flat_lang_autocomplete_setup();
    }
}

/**
 * This method gets loaded on every page to add drupal js files
 * to allow people to create a language autocomplete field using
 * data-role="flat-lang-autocomplete" to enable autocomplete and
 * data-role="flat-lang-autocomplete-destination" for the ISO code
 * once selected
 */
function flat_lang_autocomplete_setup() {

    $module_path = drupal_get_path('module', 'flat_lang_autocomplete');

    flat_lang_autocomplete_check_autocomplete_data();

    drupal_add_js($module_path . '/js/flat-lang-autocomplete.js');
    drupal_add_js([
        'flat_lang_autocomplete' => [
            'languages' => flat_lang_autocomplete_data(),
        ]], [
            'type' => 'setting',
        ]
    );
}

/**
 * Check autocomplete data or generate
 *
 * @return void
 */
function flat_lang_autocomplete_check_autocomplete_data() {

    $module_path = drupal_get_path('module', 'flat_lang_autocomplete');

    if (!file_exists($module_path . '/processed.json') || filemtime($module_path . '/name2iso.json') > filemtime($module_path . '/processed.json')) {
        flat_lang_autocomplete_data_preparation();
    }
}

/**
 * Fetch processed autocomplete data
 *
 * @return array
 */
function flat_lang_autocomplete_data() {

    $module_path = drupal_get_path('module', 'flat_lang_autocomplete');
    return json_decode(file_get_contents($module_path . '/processed.json'), true);
}

/**
 * Processing autocomplete data to allow faster
 * searches in js
 */
function flat_lang_autocomplete_data_preparation() {

    $module_path      = drupal_get_path('module', 'flat_lang_autocomplete');
    $results          = json_decode(file_get_contents($module_path . '/name2iso.json'), true);
    $data             = [];
    $prepared         = [];
    $db_custom_labels = flat_lang_autocomplete_db_get_labels();

    foreach ($results as $lang => $codes) {

        // filter duplicate codes
        $codes = array_unique($codes);

        foreach ($codes as $code) {
            $prepared[$code][] = $lang;
        }
    }

    foreach ($prepared as $code => $languages) {

        $data[$code] = [

            'code'  => $code,
            'terms' => [],
        ];

        foreach ($languages as $key => $lang) {

            if (preg_match('/\[(?P<lang>.+)\]/', $lang, $matches)) {

                if ($matches['lang'] === 'en') {
                    $data[$code]['terms'][] = trim(preg_replace('/\[(.+)\]/', '', $lang));
                }
            }
        }
    }

    $custom_labels = [];
    foreach ($db_custom_labels as $id => $label) {
        $custom_labels[$label['code']][] = $label['label'];
    }

    foreach ($custom_labels as $code => $labels) {

        if (!isset($data[$code])) {

            $data[$code] = [

                'code'  => $code,
                'terms' => [],
            ];
        }

        foreach ($labels as $label) {
            $data[$code]['terms'][] = $custom_labels[$code];
        }
    }

    file_put_contents($module_path . '/processed.json', json_encode(array_values($data), JSON_PRETTY_PRINT));
}

/**
 * Create admin page to allow users to fill in
 * custom labels
 *
 * @return array
 */
function flat_lang_autocomplete_menu() {

    $items = [

        'admin/config/flat_deposit/flat_lang_autocomplete' => [

            'title'            => 'Configure language autocomplete',
            'description'      => 'Manage labels for lang codes for the autocomplete',
            'page callback'    => 'drupal_get_form',
            'page arguments'   => ['flat_lang_autocomplete_admin'],
            'access callback'  => 'flat_lang_autocomplete_admin_access',
            'access arguments' => ['manage language autocomplete menu', 2],
            'type'             => MENU_NORMAL_ITEM,
        ],
    ];

    return $items;
}

/**
 * @param string         $op
 * @param AbstractObject $object
 *
 * @return boolean
 */
function flat_lang_autocomplete_admin_access($op, $object) {
    return user_access('manage language autocomplete menu');
}

/**
 * @return array
 */
function flat_lang_autocomplete_permission() {

    return [
        'manage language autocomplete menu' => [
            'title' => t('Manage Language Autocomplete'),
            'description' => t('Allows you to manage custom labels for the language autocomplete'),
        ],
    ];
}

/**
 * Connect admin table theme to page
 *
 * @return array
 */
function flat_lang_autocomplete_theme() {

    return [

        'flat_lang_autocomplete_admin_table' => [

            'path'           => drupal_get_path('module', 'flat_lang_autocomplete'),
            'file'           => 'includes/admin.inc',
            'render element' => 'form',
        ],
    ];
}

/**
 * Custom labels form
 *
 * @param array $form
 * @param array $form_state
 *
 * @return array
 */
function flat_lang_autocomplete_admin($form, &$form_state) {

    $module_path = drupal_get_path('module', 'flat_lang_autocomplete');

    flat_lang_autocomplete_check_autocomplete_data();

    drupal_add_js($module_path . '/js/flat-lang-autocomplete.js');
    drupal_add_js([
        'flat_lang_autocomplete' => [
            'languages' => flat_lang_autocomplete_data(),
        ]], [
            'type' => 'setting',
        ]
    );

    $form['#attached'] = [
        'css' => [
            $module_path . '/css/flat-lang-autocomplete.admin.css',
        ],
    ];

    $form['general'] = [

        '#type'   => 'vertical_tabs',
        '#weight' => 5,
    ];

    $form['general']['custom_labels'] = [

        '#type'        => 'fieldset',
        '#title'       => t('Custom Labels'),
        '#collapsible' => true,
    ];

    if ($form_state['rebuild'] == false) {

        $labels = flat_lang_autocomplete_db_get_labels();
        $form_state['custom_labels'] = [];

        foreach ($labels as $id => $label) {

            // move labels into form_state
            $form_state['custom_labels'][$id] = $label;
        }
    }

    if (isset($form_state['triggering_element'])) {

        if ($form_state['triggering_element']['#value'] == t('Remove')) {

            $id = $form_state['triggering_element']['#id'];
            unset($form_state['custom_labels'][$id]);
        }

        if ($form_state['triggering_element']['#value'] == t('Add')) {

            $code  = $form_state['values']['table']['add_label']['code'];
            $label = $form_state['values']['table']['add_label']['label'];

            if (empty($code) || empty($label)) {
                $error = t('One of the fields weren\'t properly filled in');
            }

            if (!isset($error)) {

                // add new label
                $form_state['custom_labels'][] = ['code' => $code, 'label' => $label];

                // clear input fields
                $form_state['input']['table']['add_label']['code']  = '';
                $form_state['input']['table']['add_label']['label'] = '';
            }
        }
    }

    $form['general']['custom_labels']['table'] = [

        '#type'        => 'item',
        '#title'       => t('Custom Labels'),
        '#description' => t('Custom labels for certain language codes according to the ISO-639-3 spec'),
        '#tree'        => true,
        '#theme'       => 'flat_lang_autocomplete_admin_table',
        '#prefix'      => '<div id="flat-lang-autocomplete-admin-wrapper">',
        '#suffix'      => '</div>',
    ];

    $labels = [];

    foreach ($form_state['custom_labels'] as $id => $label) {

        $labels[$id] = [

            'id' => [
                '#type' => 'hidden',
                '#value' => $id,
            ],
            'code_render' => [
                '#markup' => $label['code'],
            ],
            'code' => [
                '#type' => 'hidden',
                '#value' => $label['code'],
            ],
            'label_render' => [
                '#markup' => $label['label'],
            ],
            'label' => [
                '#type' => 'hidden',
                '#value' => $label['label'],
            ],
            'operations' => [

                '#type'       => 'submit',
                '#value'      => t('Remove'),
                '#id'         => $id,
                '#attributes' => ['class' => ['flat-lang-autocomplete-remove-submit']],
                '#submit'     => ['flat_lang_autocomplete_admin_update_fields_submit'],
                '#name'       => 'flat_lang_autocomplete_remove_button_' . $id,
                '#ajax'       => [
                    'callback' => 'flat_lang_autocomplete_admin_update_fields',
                    'wrapper'  => 'flat-lang-autocomplete-admin-wrapper',
                    'effect'   => 'none',
                    'event'    => 'click',
                ],
            ],
        ];
    }

    $add_label = [

        '#type'  => 'item',
        '#title' => t('Add another label'),
        'label'  => [
            '#type'          => 'textfield',
            '#size'          => 30,
            '#default_value' => '',
            '#prefix'        => '<div>',
            '#suffix'        => '</div>',
            '#attributes'    => ['placeholder' => 'Label', 'data-role' => 'flat-lang-autocomplete'],
        ],
        'code'  => [
            '#type'          => 'textfield',
            '#size'          => 30,
            '#default_value' => '',
            '#prefix'        => '<div>',
            '#suffix'        => '</div>',
            '#attributes'    => ['placeholder' => 'Code', 'data-role' => 'flat-lang-autocomplete-destination', 'data-flat-lang-autocomplete-ignore-prefix' => 'true'],
        ],
        'button' => [
            '#type'   => 'button',
            '#value'  => t('Add'),
            '#prefix' => '<div>',
            '#suffix' => '</div>',
            '#submit' => ['flat_lang_autocomplete_admin_update_fields_submit'],
            '#name'   => 'add_label',
            '#ajax'   => [
                'callback' => 'flat_lang_autocomplete_admin_update_fields',
                'wrapper'  => 'flat-lang-autocomplete-admin-wrapper',
                'event'    => 'click',
                'effect'   => 'none',
            ],
        ],
    ];

    if (isset($error) && !empty($error)) {

        $add_label['#title']     .= '<br /><span class="flat-lang-autocomplete-error">' . $error . '</span>';
        $add_label['#attributes'] = ['class' => ['error']];
    }

    $form['general']['custom_labels']['table']['add_label'] = $add_label;
    $form['general']['custom_labels']['table']['labels']    = $labels;

    $form['actions'] = [

        '#type' => 'actions',

        'submit' => [

            '#type'   => 'submit',
            '#value'  => t('Save Configuration'),
            '#weight' => 0,
            '#submit' => ['flat_lang_autocomplete_submit'],
        ],
        'reset' => [

            '#type'   => 'submit',
            '#value'  => t('Reset to defaults'),
            '#weight' => 1,
            '#submit' => ['flat_lang_autocomplete_submit'],
        ],
    ];

    return $form;
}

/**
 * Which part of the form have to be returned
 * when ajax is completed
 *
 * @param array $form
 * @param array $form_state
 *
 * @return array
 */
function flat_lang_autocomplete_admin_update_fields($form, &$form_state) {
    return $form['general']['custom_labels']['table'];
}

/**
 * Rebuild form when ajax is done
 *
 * @param array $form
 * @param array $form_state
 */
function flat_lang_autocomplete_admin_update_fields_submit($form, &$form_state) {
    $form_state['rebuild'] = true;
}

/**
 * Preparing form_state data for insertion to database
 *
 * @param array $form_labels
 *
 * @return array
 */
function flat_lang_autocomplete_admin_prepare_form_labels($form_labels) {

    $labels = [];

    foreach ($form_labels as $label) {
        $labels[][] = ['code' => $label['code'],  'label' => $label['label']];
    }

    return $labels;
}

/**
 * Saving custom labels to db
 *
 * @param array $form
 * @param array $form_state
 */
function flat_lang_autocomplete_submit($form, &$form_state) {

    if ($form_state['triggering_element']['#value'] == t('Reset to defaults')) {

        $form_state['redirect'] = 'admin/config/flat_deposit/flat_lang_autocomplete';
        drupal_set_message(t('Custom labels form was successfully reset'));

    } else {

        $labels = flat_lang_autocomplete_admin_prepare_form_labels($form_state['custom_labels']);
        flat_lang_autocomplete_db_commit_labels($labels);

        drupal_set_message(t('Custom labels were successfully saved'));
    }
}
